apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tuition-saas
resources:
  - namespace.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-hpa.yaml
  - frontend-pdb.yaml
