ALTER TABLE coachings
  ADD COLUMN IF NOT EXISTS payment_upi_id VARCHAR(80),
  ADD COLUMN IF NOT EXISTS payment_qr_url TEXT,
  ADD COLUMN IF NOT EXISTS bank_account_name VARCHAR(150),
  ADD COLUMN IF NOT EXISTS bank_account_number VARCHAR(40),
  ADD COLUMN IF NOT EXISTS bank_ifsc VARCHAR(20),
  ADD COLUMN IF NOT EXISTS bank_name VARCHAR(120);

ALTER TABLE students
  ADD COLUMN IF NOT EXISTS email VARCHAR(150);
