DROP POLICY IF EXISTS tenant_isolation_refresh_tokens ON refresh_tokens;
DROP POLICY IF EXISTS tenant_isolation_qr_scan_events ON qr_scan_events;
DROP POLICY IF EXISTS tenant_isolation_notification_templates ON notification_templates;
DROP POLICY IF EXISTS tenant_isolation_notifications ON notifications;
DROP POLICY IF EXISTS tenant_isolation_attendance ON attendance;
DROP POLICY IF EXISTS tenant_isolation_payment_logs ON payment_logs;
DROP POLICY IF EXISTS tenant_isolation_payments ON payments;
DROP POLICY IF EXISTS tenant_isolation_fee_accounts ON student_fee_accounts;
DROP POLICY IF EXISTS tenant_isolation_students ON students;
DROP POLICY IF EXISTS tenant_isolation_fee_plans ON fee_plans;
DROP POLICY IF EXISTS tenant_isolation_users ON users;

ALTER TABLE IF EXISTS refresh_tokens DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS qr_scan_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS notification_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payment_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS student_fee_accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS students DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS fee_plans DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS users DISABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS qr_scan_events DROP CONSTRAINT IF EXISTS ck_qr_scan_events_outcome;
ALTER TABLE IF EXISTS notification_templates DROP CONSTRAINT IF EXISTS ck_notification_templates_channel;
ALTER TABLE IF EXISTS notifications DROP CONSTRAINT IF EXISTS ck_notifications_status;
ALTER TABLE IF EXISTS notifications DROP CONSTRAINT IF EXISTS ck_notifications_channel;
ALTER TABLE IF EXISTS attendance DROP CONSTRAINT IF EXISTS ck_attendance_status;
ALTER TABLE IF EXISTS attendance DROP CONSTRAINT IF EXISTS ck_attendance_source;
ALTER TABLE IF EXISTS payments DROP CONSTRAINT IF EXISTS ck_payments_status;
ALTER TABLE IF EXISTS payments DROP CONSTRAINT IF EXISTS ck_payments_payment_mode;
ALTER TABLE IF EXISTS payments DROP CONSTRAINT IF EXISTS ck_payments_method;
ALTER TABLE IF EXISTS payments DROP CONSTRAINT IF EXISTS ck_payments_amount;
ALTER TABLE IF EXISTS student_fee_accounts DROP CONSTRAINT IF EXISTS ck_sfa_status;
ALTER TABLE IF EXISTS student_fee_accounts DROP CONSTRAINT IF EXISTS ck_sfa_amounts;
ALTER TABLE IF EXISTS students DROP CONSTRAINT IF EXISTS ck_students_status;
ALTER TABLE IF EXISTS fee_plans DROP CONSTRAINT IF EXISTS ck_fee_plans_due_day;
ALTER TABLE IF EXISTS fee_plans DROP CONSTRAINT IF EXISTS ck_fee_plans_amount_total;
ALTER TABLE IF EXISTS fee_plans DROP CONSTRAINT IF EXISTS ck_fee_plans_fee_type;
ALTER TABLE IF EXISTS users DROP CONSTRAINT IF EXISTS ck_users_role;

ALTER TABLE IF EXISTS qr_scan_events DROP CONSTRAINT IF EXISTS fk_qr_scan_events_student_tenant;
ALTER TABLE IF EXISTS notifications DROP CONSTRAINT IF EXISTS fk_notifications_student_tenant;
ALTER TABLE IF EXISTS attendance DROP CONSTRAINT IF EXISTS fk_attendance_scanned_by_tenant;
ALTER TABLE IF EXISTS attendance DROP CONSTRAINT IF EXISTS fk_attendance_student_tenant;
ALTER TABLE IF EXISTS payment_logs DROP CONSTRAINT IF EXISTS fk_payment_logs_payment_tenant;
ALTER TABLE IF EXISTS payments DROP CONSTRAINT IF EXISTS fk_payments_created_by_tenant;
ALTER TABLE IF EXISTS payments DROP CONSTRAINT IF EXISTS fk_payments_fee_account_tenant;
ALTER TABLE IF EXISTS payments DROP CONSTRAINT IF EXISTS fk_payments_student_tenant;
ALTER TABLE IF EXISTS student_fee_accounts DROP CONSTRAINT IF EXISTS fk_sfa_fee_plan_tenant;
ALTER TABLE IF EXISTS student_fee_accounts DROP CONSTRAINT IF EXISTS fk_sfa_student_tenant;
ALTER TABLE IF EXISTS students DROP CONSTRAINT IF EXISTS fk_students_teacher_tenant;
ALTER TABLE IF EXISTS students DROP CONSTRAINT IF EXISTS fk_students_fee_plan_tenant;
ALTER TABLE IF EXISTS refresh_tokens DROP CONSTRAINT IF EXISTS fk_refresh_tokens_user_tenant;

ALTER TABLE IF EXISTS notification_templates DROP CONSTRAINT IF EXISTS uq_notification_templates_scope;
ALTER TABLE IF EXISTS attendance DROP CONSTRAINT IF EXISTS uq_attendance_coaching_student_date;
ALTER TABLE IF EXISTS payments DROP CONSTRAINT IF EXISTS uq_payments_coaching_id_id;
ALTER TABLE IF EXISTS student_fee_accounts DROP CONSTRAINT IF EXISTS uq_student_fee_accounts_coaching_student;
ALTER TABLE IF EXISTS student_fee_accounts DROP CONSTRAINT IF EXISTS uq_student_fee_accounts_coaching_id_id;
ALTER TABLE IF EXISTS students DROP CONSTRAINT IF EXISTS uq_students_coaching_student_code;
ALTER TABLE IF EXISTS students DROP CONSTRAINT IF EXISTS uq_students_coaching_id_id;
ALTER TABLE IF EXISTS fee_plans DROP CONSTRAINT IF EXISTS uq_fee_plans_coaching_name;
ALTER TABLE IF EXISTS fee_plans DROP CONSTRAINT IF EXISTS uq_fee_plans_coaching_id_id;
ALTER TABLE IF EXISTS users DROP CONSTRAINT IF EXISTS uq_users_coaching_email;
ALTER TABLE IF EXISTS users DROP CONSTRAINT IF EXISTS uq_users_coaching_id_id;
ALTER TABLE IF EXISTS coachings DROP CONSTRAINT IF EXISTS uq_coachings_email;
ALTER TABLE IF EXISTS coachings DROP CONSTRAINT IF EXISTS uq_coachings_code;

ALTER TABLE IF EXISTS qr_scan_events DROP CONSTRAINT IF EXISTS fk_qr_scan_events_coaching;
ALTER TABLE IF EXISTS notification_templates DROP CONSTRAINT IF EXISTS fk_notification_templates_coaching;
ALTER TABLE IF EXISTS notifications DROP CONSTRAINT IF EXISTS fk_notifications_coaching;
ALTER TABLE IF EXISTS attendance DROP CONSTRAINT IF EXISTS fk_attendance_coaching;
ALTER TABLE IF EXISTS payment_logs DROP CONSTRAINT IF EXISTS fk_payment_logs_coaching;
ALTER TABLE IF EXISTS payments DROP CONSTRAINT IF EXISTS fk_payments_coaching;
ALTER TABLE IF EXISTS student_fee_accounts DROP CONSTRAINT IF EXISTS fk_student_fee_accounts_coaching;
ALTER TABLE IF EXISTS students DROP CONSTRAINT IF EXISTS fk_students_coaching;
ALTER TABLE IF EXISTS fee_plans DROP CONSTRAINT IF EXISTS fk_fee_plans_coaching;
ALTER TABLE IF EXISTS refresh_tokens DROP CONSTRAINT IF EXISTS fk_refresh_tokens_coaching;
ALTER TABLE IF EXISTS users DROP CONSTRAINT IF EXISTS fk_users_coaching;
