const dotenv = require('dotenv');

dotenv.config();

const env = {
  port: Number(process.env.PORT || 4000),
  nodeEnv: process.env.NODE_ENV || 'development',
  databaseUrl: process.env.DATABASE_URL,
  dbSslRejectUnauthorized: String(process.env.DB_SSL_REJECT_UNAUTHORIZED || 'false').toLowerCase() === 'true',
  dbPoolMax: Number(process.env.DB_POOL_MAX || 30),
  dbIdleTimeoutMs: Number(process.env.DB_IDLE_TIMEOUT_MS || 30000),
  dbConnectionTimeoutMs: Number(process.env.DB_CONNECTION_TIMEOUT_MS || 10000),
  dbMaxUses: Number(process.env.DB_MAX_USES || 7500),
  dbKeepAlive: String(process.env.DB_KEEPALIVE || 'true').toLowerCase() === 'true',
  dbRetryAttempts: Number(process.env.DB_RETRY_ATTEMPTS || 2),
  dbRetryDelayMs: Number(process.env.DB_RETRY_DELAY_MS || 120),
  dbLogSlowQueries: String(process.env.DB_LOG_SLOW_QUERIES || 'true').toLowerCase() === 'true',
  dbSlowQueryMs: Number(process.env.DB_SLOW_QUERY_MS || 250),
  metricsEnabled: String(process.env.METRICS_ENABLED || 'true').toLowerCase() === 'true',
  metricsToken: process.env.METRICS_TOKEN || '',
  redisEnabled: String(process.env.REDIS_ENABLED || 'false').toLowerCase() === 'true',
  redisUrl: process.env.REDIS_URL || '',
  sqsEnabled: String(process.env.SQS_ENABLED || 'false').toLowerCase() === 'true',
  awsRegion: process.env.AWS_REGION || 'ap-south-1',
  sqsReminderQueueUrl: process.env.SQS_REMINDER_QUEUE_URL || '',
  sqsLongPollSeconds: Number(process.env.SQS_LONG_POLL_SECONDS || 20),
  partitionDualWrite: String(process.env.PARTITION_DUAL_WRITE || 'false').toLowerCase() === 'true',
  partitionReadTables: String(process.env.PARTITION_READ_TABLES || 'false').toLowerCase() === 'true',
  jwtAccessSecret: process.env.JWT_ACCESS_SECRET || 'dev_access_secret',
  jwtRefreshSecret: process.env.JWT_REFRESH_SECRET || 'dev_refresh_secret',
  jwtAccessExpires: process.env.JWT_ACCESS_EXPIRES || '15m',
  jwtRefreshExpires: process.env.JWT_REFRESH_EXPIRES || '7d',
  razorpayKeyId: process.env.RAZORPAY_KEY_ID || '',
  razorpayKeySecret: process.env.RAZORPAY_KEY_SECRET || '',
  razorpayWebhookSecret: process.env.RAZORPAY_WEBHOOK_SECRET || '',
  corsOrigin: process.env.CORS_ORIGIN || '*',
  reminderCronExpression: process.env.REMINDER_CRON_EXPRESSION || '0 9 * * *',
  notificationWorkerCronExpression: process.env.NOTIFICATION_WORKER_CRON_EXPRESSION || '*/5 * * * *',
  reminderTimezone: process.env.REMINDER_TIMEZONE || 'Asia/Kolkata',
  reminderChannels: (process.env.REMINDER_CHANNELS || 'sms,email').split(',').map((v) => v.trim()).filter(Boolean),
  notificationMaxRetries: Number(process.env.NOTIFICATION_MAX_RETRIES || 5),
  smtpHost: process.env.SMTP_HOST || '',
  smtpPort: Number(process.env.SMTP_PORT || 587),
  smtpSecure: String(process.env.SMTP_SECURE || 'false').toLowerCase() === 'true',
  smtpUser: process.env.SMTP_USER || '',
  smtpPass: process.env.SMTP_PASS || '',
  smtpFrom: process.env.SMTP_FROM || 'no-reply@tution.app',
  ownerAlertEmail: process.env.OWNER_ALERT_EMAIL || '',
  smsProviderUrl: process.env.SMS_PROVIDER_URL || '',
  smsProviderToken: process.env.SMS_PROVIDER_TOKEN || '',
  twilioAccountSid: process.env.TWILIO_ACCOUNT_SID || '',
  twilioAuthToken: process.env.TWILIO_AUTH_TOKEN || '',
  twilioFromNumber: process.env.TWILIO_FROM_NUMBER || '',
  twilioMessagingServiceSid: process.env.TWILIO_MESSAGING_SERVICE_SID || '',
  whatsappProviderUrl: process.env.WHATSAPP_PROVIDER_URL || '',
  whatsappProviderToken: process.env.WHATSAPP_PROVIDER_TOKEN || '',
  whatsappSender: process.env.WHATSAPP_SENDER || '',
  receiptBaseUrl: process.env.RECEIPT_BASE_URL || ''
};

module.exports = env;
